# Generated by Django 3.2.4 on 2021-07-05 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('district', models.CharField(max_length=150, verbose_name='Район')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Дом')),
                ('postcode', models.PositiveBigIntegerField(verbose_name='Индекс')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Расположение на карте')),
                ('requisites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реквизиты')),
                ('starting_work_weekdays', models.TimeField(blank=True, null=True, verbose_name='Начало работы в будние')),
                ('finishing_work_weekdays', models.TimeField(blank=True, null=True, verbose_name='Конец работы в будние')),
                ('starting_work_weekends', models.TimeField(blank=True, null=True, verbose_name='Начало работы по выходным')),
                ('finishing_work_weekends', models.TimeField(blank=True, null=True, verbose_name='Конец работы по выходным')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимости',
                'ordering': ['lesson_type', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50, verbose_name='Длительность')),
                ('days', models.CharField(max_length=100, verbose_name='Дни')),
                ('hours', models.CharField(max_length=100, verbose_name='Часы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.costs', verbose_name='Цена')),
                ('lesson_age', models.ManyToManyField(to='SmStSi.AgeGroups', verbose_name='Возрастная группа')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='LessonsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('improves_skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='Развивающиеся навыки')),
            ],
            options={
                'verbose_name': 'Тип урока',
                'verbose_name_plural': 'Типы уроков',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('photo_link', models.ImageField(upload_to='post_files', verbose_name='Ссылка на фото')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_files', verbose_name='Ссылка на видео')),
                ('short_description', models.CharField(blank=True, max_length=127, null=True, verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=False, verbose_name='Выводится в галерею')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.lessons', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(max_length=254, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип договора')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договора',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.specialization', verbose_name='Специализация')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='StudioDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О нас')),
                ('philosophy', models.TextField(blank=True, null=True, verbose_name='Философия центра')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='Наша миссия')),
                ('sight', models.TextField(blank=True, null=True, verbose_name='Наш взгляд')),
                ('target', models.TextField(blank=True, null=True, verbose_name='Наша цель')),
                ('logotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.media', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'О Нас',
                'verbose_name_plural': 'О Нас',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('experience', models.CharField(blank=True, max_length=150, null=True, verbose_name='Опыт')),
                ('education', models.CharField(blank=True, max_length=150, null=True, verbose_name='Образование')),
                ('ad_information', models.TextField(blank=True, null=True, verbose_name='ad_information')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актив')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.specialization', verbose_name='Специализация')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('message', models.TextField(verbose_name='Текст отзыва')),
                ('star_choice_1', models.CharField(max_length=5, verbose_name='Рейтинг1')),
                ('star_choice_2', models.CharField(max_length=5, verbose_name='Рейтинг2')),
                ('star_choice_3', models.CharField(max_length=5, verbose_name='Рейтинг3')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.lessons', verbose_name='Занятие')),
                ('staff', models.ManyToManyField(to='SmStSi.Staff', verbose_name='Сотрудник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NewsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('digest', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое содержание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('media_url', models.URLField(blank=True, default='', null=True, verbose_name='Медиассылка')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.media', verbose_name='Медиа')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmStSi.lessonstype', verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-modified', 'title'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='staff',
            field=models.ManyToManyField(to='SmStSi.Staff', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.lessonstype', verbose_name='Тип урока'),
        ),
        migrations.AddField(
            model_name='costs',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.lessonstype', verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='costs',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmStSi.staff', verbose_name='Сотрудник'),
        ),
    ]
