# Generated by Django 3.2.5 on 2021-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='location',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Расположение на карте'),
        ),
    ]
