# Generated by Django 3.2.5 on 2021-07-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['created_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='date_add',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='contract',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contract_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='team.contracttype', verbose_name='Тип договора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Вакансия открыта'),
        ),
    ]
